name: Global Invest Bot

on:
  schedule:
    - cron: '0 2 * * *' # 北京时间 10:00 运行
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install
        run: pip install yfinance pandas google-genai
      - name: Run
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py
      - name: Auto Log
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Data log updated: ${{ github.event.head_commit.timestamp }}"
          file_pattern: 'global_investment_log.csv'